import type { EditorialEntry, EditorialImage } from "./editorial";

const BLOG_CARD_IMAGE_OVERRIDES: Record<string, string> = {
  "best-ai-session-recap-event-transcription-tools-2026": "/blog-images/ai-session-recap.webp",
  "top-15-event-operations-chatgpt-eventhex": "/blog-images/event-operations-ai.webp",
  "event-management-mcp-server-guide": "/blog-images/event-management-mcp.webp",
  "ultimate-budget-template-corporate-meetings": "/blog-images/corporate-event-budget.webp",
  "corporate-event-budget-template": "/blog-images/corporate-event-budget.webp",
  "exhibitor-portal-vs-spreadsheet-chaos-exhibitor-management-software": "/blog-images/exhibitor-portal.webp",
  "why-traditional-exhibitor-management-fails-self-service-portals": "/blog-images/exhibitor-portal.webp",
  "on-site-event-emergency-checklist-items": "/blog-images/venue-emergency-check.webp",
  "battle-against-duplicate-badge-printing-high-volume-conferences": "/blog-images/badge-printing-system.webp",
  "speaker-management-software-blueprint-conference-agendas": "/blog-images/conference-agenda-planning.webp",
  "traditional-conference-agendas-fail-session-scheduling-multi-track-agenda-tools": "/blog-images/conference-agenda-planning.webp",
  "event-accessibility-guidelines-new-standards": "/blog-images/accessible-events.webp",
  "next-wave-privacy-first-attendee-analytics-2026": "/blog-images/privacy-first-analytics.webp",
  "the-shift-to-privacy-first-attendee-analytics-in-2026": "/blog-images/privacy-first-analytics.webp",
  "how-to-plan-carbon-neutral-corporate-event-sustainable-planning": "/blog-images/sustainable-corporate-event.webp",
  "conference-organizers-playbook-call-for-papers-software": "/blog-images/call-for-papers-review.webp",
  "how-to-pitch-sponsorship-for-local-charity-runs": "/blog-images/charity-run-sponsorship.webp",
  "the-b2b-event-playbook-boosting-attendee-retention-in-2026": "/blog-images/attendee-retention.webp",
  "how-event-organizers-saved-40-hours-on-badge-printing": "/blog-images/badge-printing-system.webp",
  "beyond-the-ramp-event-accessibility-guidelines-and-new-standards-to-know-in-2026": "/blog-images/accessible-events.webp",
  "why-40-percent-of-attendees-skip-event-registration-forms": "/blog-images/registration-forms-friction.webp",
  "on-site-event-emergency-checklist": "/blog-images/venue-emergency-check.webp",
  "google-drive-vs-ai-face-matching": "/blog-images/event-photo-delivery.webp",
  "mastering-corporate-meeting-budgets-free-template-cost-control-strategies": "/blog-images/corporate-event-budget.webp",
  "zero-fee-blueprint-sell-tickets-with-stripe-keep-revenue": "/blog-images/badge-printing-system.webp",
  "10-vital-items-on-site-event-emergency-checklist": "/blog-images/venue-emergency-check.webp",
  "how-event-organizers-saved-40-hours-badge-printing": "/blog-images/badge-printing-system.webp",
  "how-ai-video-highlights-revolutionizing-post-event-retargeting": "/blog-images/ai-session-recap.webp",
  "how-to-coordinate-50-event-speakers-without-spreadsheet-chaos": "/blog-images/conference-agenda-planning.webp",
  "10-vital-items-onsite-event-emergency-checklist": "/blog-images/venue-emergency-check.webp",
  "why-90-attendees-never-see-event-photos-ai-fixes-it": "/blog-images/event-photo-delivery.webp",
  "manual-matchmaking-vs-ai-networking-why-hosts-are-switching": "/blog-images/attendee-retention.webp",
  "why-unreliable-venue-wifi-ruined-your-last-event-check-in-how-to-fix-it": "/blog-images/badge-printing-system.webp",
  "why-40-percent-attendees-skip-event-registration-forms-how-to-fix-it": "/blog-images/registration-forms-friction.webp",
  "why-70-percent-attendees-skip-post-event-surveys-how-to-fix-it": "/blog-images/attendee-retention.webp",
  "why-conference-insights-lost-ai-session-summaries": "/blog-images/ai-session-recap.webp",
  "why-80-of-event-sponsors-never-return-how-to-prove-roi-with-real-time-data": "/blog-images/charity-run-sponsorship.webp",
  "google-drive-vs-ai-face-matching-event-photo-sharing": "/blog-images/event-photo-delivery.webp",
  "how-to-solve-event-check-in-queue-bottleneck-badge-printing": "/blog-images/badge-printing-system.webp",
  "manual-matchmaking-vs-ai-networking-b2b-event-hosts": "/blog-images/attendee-retention.webp",
  "automated-event-notifications-guide": "/blog-images/event-management-mcp.webp",
  "ai-event-photography-software-guide": "/blog-images/event-photo-delivery.webp",
  "ultimate-guide-onsite-event-badge-printing-software": "/blog-images/badge-printing-system.webp",
  "exhibitor-lead-retrieval-software-guide": "/blog-images/exhibitor-portal.webp",
  "unlocking-post-event-engagement-with-an-automatic-certificate-generator": "/blog-images/attendee-retention.webp",
  "how-to-build-a-viral-event-marketing-engine-using-an-advocacy-poster-creator": "/blog-images/exhibitor-portal.webp",
  "breaking-barriers-why-real-time-live-transcription-is-essential-for-modern-events": "/blog-images/ai-session-recap.webp",
  "smart-event-ticketing-access-control": "/blog-images/badge-printing-system.webp",
  "ai-event-photo-gallery-guide": "/blog-images/event-photo-delivery.webp",
  "live-event-translation-accessibility-guide": "/blog-images/accessible-events.webp",
  "ai-event-matchmaking-networking-guide": "/blog-images/attendee-retention.webp",
  "event-gamification-strategies-guide-2026": "/blog-images/attendee-retention.webp",
  "the-era-of-hyper-personalization-how-ai-is-reshaping-attendee-experiences-in-2026": "/blog-images/attendee-retention.webp",
  "the-future-of-event-planning-how-eventhex-ai-is-replacing-spreadsheet-chaos-with-ai-powered-brilliance": "/blog-images/event-operations-ai.webp",
  "centralized-dashboard-event-management": "/blog-images/event-operations-ai.webp",
  "modern-event-platforms-future-ready-events-eventhex": "/blog-images/event-operations-ai.webp",
  "attendee-engagement-centralized-event-intelligence": "/blog-images/event-operations-ai.webp",
  "attendee-engagement-event-technology": "/blog-images/attendee-retention.webp",
  "first-time-exhibitor-management-mistakes": "/blog-images/exhibitor-portal.webp",
  "why-your-event-needs-multi-channel-campaigns-the-email-whatsapp-strategy-that-boosts-attendance-by-40": "/blog-images/event-management-mcp.webp",
  "eventhex-the-best-for-end-to-end-event-management": "/blog-images/event-operations-ai.webp",
  "eventhex-whatsapp-and-email-marketing-boost-attendance": "/blog-images/event-management-mcp.webp",
  "25-best-event-management-software-tools-2026-edition": "/blog-images/event-operations-ai.webp",
  "ai-driven-event-networking-by-eventhex-ai-smart-connect": "/blog-images/attendee-retention.webp",
  "maximize-revenue-with-event-ticketing": "/blog-images/badge-printing-system.webp",
  "attendee-retention-crisis-how-ai-powered-personalization-is-transforming-event": "/blog-images/attendee-retention.webp",
  "revolutionize-events-with-event-management-software": "/blog-images/event-operations-ai.webp",
};

export function getEditorialCardImage(item: EditorialEntry): EditorialImage | null {
  const overrideSrc = item.kind === "blog" ? BLOG_CARD_IMAGE_OVERRIDES[item.slug] : undefined;

  if (!overrideSrc) {
    return item.image;
  }

  return {
    src: overrideSrc,
    alt: item.title,
    width: 1200,
    height: 675,
  };
}
