export interface PhoneCountry {
  country: string;
  dial: string;
  name: string;
}

export const phoneCountries: PhoneCountry[] = [
  {"country":"AF","dial":"+93","name":"Afghanistan"},
  {"country":"AX","dial":"+358","name":"Åland Islands"},
  {"country":"AL","dial":"+355","name":"Albania"},
  {"country":"DZ","dial":"+213","name":"Algeria"},
  {"country":"AS","dial":"+1","name":"American Samoa"},
  {"country":"AD","dial":"+376","name":"Andorra"},
  {"country":"AO","dial":"+244","name":"Angola"},
  {"country":"AI","dial":"+1","name":"Anguilla"},
  {"country":"AG","dial":"+1","name":"Antigua & Barbuda"},
  {"country":"AR","dial":"+54","name":"Argentina"},
  {"country":"AM","dial":"+374","name":"Armenia"},
  {"country":"AW","dial":"+297","name":"Aruba"},
  {"country":"AC","dial":"+247","name":"Ascension Island"},
  {"country":"AU","dial":"+61","name":"Australia"},
  {"country":"AT","dial":"+43","name":"Austria"},
  {"country":"AZ","dial":"+994","name":"Azerbaijan"},
  {"country":"BS","dial":"+1","name":"Bahamas"},
  {"country":"BH","dial":"+973","name":"Bahrain"},
  {"country":"BD","dial":"+880","name":"Bangladesh"},
  {"country":"BB","dial":"+1","name":"Barbados"},
  {"country":"BY","dial":"+375","name":"Belarus"},
  {"country":"BE","dial":"+32","name":"Belgium"},
  {"country":"BZ","dial":"+501","name":"Belize"},
  {"country":"BJ","dial":"+229","name":"Benin"},
  {"country":"BM","dial":"+1","name":"Bermuda"},
  {"country":"BT","dial":"+975","name":"Bhutan"},
  {"country":"BO","dial":"+591","name":"Bolivia"},
  {"country":"BA","dial":"+387","name":"Bosnia & Herzegovina"},
  {"country":"BW","dial":"+267","name":"Botswana"},
  {"country":"BR","dial":"+55","name":"Brazil"},
  {"country":"IO","dial":"+246","name":"British Indian Ocean Territory"},
  {"country":"VG","dial":"+1","name":"British Virgin Islands"},
  {"country":"BN","dial":"+673","name":"Brunei"},
  {"country":"BG","dial":"+359","name":"Bulgaria"},
  {"country":"BF","dial":"+226","name":"Burkina Faso"},
  {"country":"BI","dial":"+257","name":"Burundi"},
  {"country":"KH","dial":"+855","name":"Cambodia"},
  {"country":"CM","dial":"+237","name":"Cameroon"},
  {"country":"CA","dial":"+1","name":"Canada"},
  {"country":"CV","dial":"+238","name":"Cape Verde"},
  {"country":"BQ","dial":"+599","name":"Caribbean Netherlands"},
  {"country":"KY","dial":"+1","name":"Cayman Islands"},
  {"country":"CF","dial":"+236","name":"Central African Republic"},
  {"country":"TD","dial":"+235","name":"Chad"},
  {"country":"CL","dial":"+56","name":"Chile"},
  {"country":"CN","dial":"+86","name":"China"},
  {"country":"CX","dial":"+61","name":"Christmas Island"},
  {"country":"CC","dial":"+61","name":"Cocos (Keeling) Islands"},
  {"country":"CO","dial":"+57","name":"Colombia"},
  {"country":"KM","dial":"+269","name":"Comoros"},
  {"country":"CG","dial":"+242","name":"Congo - Brazzaville"},
  {"country":"CD","dial":"+243","name":"Congo - Kinshasa"},
  {"country":"CK","dial":"+682","name":"Cook Islands"},
  {"country":"CR","dial":"+506","name":"Costa Rica"},
  {"country":"CI","dial":"+225","name":"Côte d’Ivoire"},
  {"country":"HR","dial":"+385","name":"Croatia"},
  {"country":"CU","dial":"+53","name":"Cuba"},
  {"country":"CW","dial":"+599","name":"Curaçao"},
  {"country":"CY","dial":"+357","name":"Cyprus"},
  {"country":"CZ","dial":"+420","name":"Czechia"},
  {"country":"DK","dial":"+45","name":"Denmark"},
  {"country":"DJ","dial":"+253","name":"Djibouti"},
  {"country":"DM","dial":"+1","name":"Dominica"},
  {"country":"DO","dial":"+1","name":"Dominican Republic"},
  {"country":"EC","dial":"+593","name":"Ecuador"},
  {"country":"EG","dial":"+20","name":"Egypt"},
  {"country":"SV","dial":"+503","name":"El Salvador"},
  {"country":"GQ","dial":"+240","name":"Equatorial Guinea"},
  {"country":"ER","dial":"+291","name":"Eritrea"},
  {"country":"EE","dial":"+372","name":"Estonia"},
  {"country":"SZ","dial":"+268","name":"Eswatini"},
  {"country":"ET","dial":"+251","name":"Ethiopia"},
  {"country":"FK","dial":"+500","name":"Falkland Islands"},
  {"country":"FO","dial":"+298","name":"Faroe Islands"},
  {"country":"FJ","dial":"+679","name":"Fiji"},
  {"country":"FI","dial":"+358","name":"Finland"},
  {"country":"FR","dial":"+33","name":"France"},
  {"country":"GF","dial":"+594","name":"French Guiana"},
  {"country":"PF","dial":"+689","name":"French Polynesia"},
  {"country":"GA","dial":"+241","name":"Gabon"},
  {"country":"GM","dial":"+220","name":"Gambia"},
  {"country":"GE","dial":"+995","name":"Georgia"},
  {"country":"DE","dial":"+49","name":"Germany"},
  {"country":"GH","dial":"+233","name":"Ghana"},
  {"country":"GI","dial":"+350","name":"Gibraltar"},
  {"country":"GR","dial":"+30","name":"Greece"},
  {"country":"GL","dial":"+299","name":"Greenland"},
  {"country":"GD","dial":"+1","name":"Grenada"},
  {"country":"GP","dial":"+590","name":"Guadeloupe"},
  {"country":"GU","dial":"+1","name":"Guam"},
  {"country":"GT","dial":"+502","name":"Guatemala"},
  {"country":"GG","dial":"+44","name":"Guernsey"},
  {"country":"GN","dial":"+224","name":"Guinea"},
  {"country":"GW","dial":"+245","name":"Guinea-Bissau"},
  {"country":"GY","dial":"+592","name":"Guyana"},
  {"country":"HT","dial":"+509","name":"Haiti"},
  {"country":"HN","dial":"+504","name":"Honduras"},
  {"country":"HK","dial":"+852","name":"Hong Kong SAR China"},
  {"country":"HU","dial":"+36","name":"Hungary"},
  {"country":"IS","dial":"+354","name":"Iceland"},
  {"country":"IN","dial":"+91","name":"India"},
  {"country":"ID","dial":"+62","name":"Indonesia"},
  {"country":"IR","dial":"+98","name":"Iran"},
  {"country":"IQ","dial":"+964","name":"Iraq"},
  {"country":"IE","dial":"+353","name":"Ireland"},
  {"country":"IM","dial":"+44","name":"Isle of Man"},
  {"country":"IL","dial":"+972","name":"Israel"},
  {"country":"IT","dial":"+39","name":"Italy"},
  {"country":"JM","dial":"+1","name":"Jamaica"},
  {"country":"JP","dial":"+81","name":"Japan"},
  {"country":"JE","dial":"+44","name":"Jersey"},
  {"country":"JO","dial":"+962","name":"Jordan"},
  {"country":"KZ","dial":"+7","name":"Kazakhstan"},
  {"country":"KE","dial":"+254","name":"Kenya"},
  {"country":"KI","dial":"+686","name":"Kiribati"},
  {"country":"XK","dial":"+383","name":"Kosovo"},
  {"country":"KW","dial":"+965","name":"Kuwait"},
  {"country":"KG","dial":"+996","name":"Kyrgyzstan"},
  {"country":"LA","dial":"+856","name":"Laos"},
  {"country":"LV","dial":"+371","name":"Latvia"},
  {"country":"LB","dial":"+961","name":"Lebanon"},
  {"country":"LS","dial":"+266","name":"Lesotho"},
  {"country":"LR","dial":"+231","name":"Liberia"},
  {"country":"LY","dial":"+218","name":"Libya"},
  {"country":"LI","dial":"+423","name":"Liechtenstein"},
  {"country":"LT","dial":"+370","name":"Lithuania"},
  {"country":"LU","dial":"+352","name":"Luxembourg"},
  {"country":"MO","dial":"+853","name":"Macao SAR China"},
  {"country":"MG","dial":"+261","name":"Madagascar"},
  {"country":"MW","dial":"+265","name":"Malawi"},
  {"country":"MY","dial":"+60","name":"Malaysia"},
  {"country":"MV","dial":"+960","name":"Maldives"},
  {"country":"ML","dial":"+223","name":"Mali"},
  {"country":"MT","dial":"+356","name":"Malta"},
  {"country":"MH","dial":"+692","name":"Marshall Islands"},
  {"country":"MQ","dial":"+596","name":"Martinique"},
  {"country":"MR","dial":"+222","name":"Mauritania"},
  {"country":"MU","dial":"+230","name":"Mauritius"},
  {"country":"YT","dial":"+262","name":"Mayotte"},
  {"country":"MX","dial":"+52","name":"Mexico"},
  {"country":"FM","dial":"+691","name":"Micronesia"},
  {"country":"MD","dial":"+373","name":"Moldova"},
  {"country":"MC","dial":"+377","name":"Monaco"},
  {"country":"MN","dial":"+976","name":"Mongolia"},
  {"country":"ME","dial":"+382","name":"Montenegro"},
  {"country":"MS","dial":"+1","name":"Montserrat"},
  {"country":"MA","dial":"+212","name":"Morocco"},
  {"country":"MZ","dial":"+258","name":"Mozambique"},
  {"country":"MM","dial":"+95","name":"Myanmar (Burma)"},
  {"country":"NA","dial":"+264","name":"Namibia"},
  {"country":"NR","dial":"+674","name":"Nauru"},
  {"country":"NP","dial":"+977","name":"Nepal"},
  {"country":"NL","dial":"+31","name":"Netherlands"},
  {"country":"NC","dial":"+687","name":"New Caledonia"},
  {"country":"NZ","dial":"+64","name":"New Zealand"},
  {"country":"NI","dial":"+505","name":"Nicaragua"},
  {"country":"NE","dial":"+227","name":"Niger"},
  {"country":"NG","dial":"+234","name":"Nigeria"},
  {"country":"NU","dial":"+683","name":"Niue"},
  {"country":"NF","dial":"+672","name":"Norfolk Island"},
  {"country":"KP","dial":"+850","name":"North Korea"},
  {"country":"MK","dial":"+389","name":"North Macedonia"},
  {"country":"MP","dial":"+1","name":"Northern Mariana Islands"},
  {"country":"NO","dial":"+47","name":"Norway"},
  {"country":"OM","dial":"+968","name":"Oman"},
  {"country":"PK","dial":"+92","name":"Pakistan"},
  {"country":"PW","dial":"+680","name":"Palau"},
  {"country":"PS","dial":"+970","name":"Palestinian Territories"},
  {"country":"PA","dial":"+507","name":"Panama"},
  {"country":"PG","dial":"+675","name":"Papua New Guinea"},
  {"country":"PY","dial":"+595","name":"Paraguay"},
  {"country":"PE","dial":"+51","name":"Peru"},
  {"country":"PH","dial":"+63","name":"Philippines"},
  {"country":"PL","dial":"+48","name":"Poland"},
  {"country":"PT","dial":"+351","name":"Portugal"},
  {"country":"PR","dial":"+1","name":"Puerto Rico"},
  {"country":"QA","dial":"+974","name":"Qatar"},
  {"country":"RE","dial":"+262","name":"Réunion"},
  {"country":"RO","dial":"+40","name":"Romania"},
  {"country":"RU","dial":"+7","name":"Russia"},
  {"country":"RW","dial":"+250","name":"Rwanda"},
  {"country":"WS","dial":"+685","name":"Samoa"},
  {"country":"SM","dial":"+378","name":"San Marino"},
  {"country":"ST","dial":"+239","name":"São Tomé & Príncipe"},
  {"country":"SA","dial":"+966","name":"Saudi Arabia"},
  {"country":"SN","dial":"+221","name":"Senegal"},
  {"country":"RS","dial":"+381","name":"Serbia"},
  {"country":"SC","dial":"+248","name":"Seychelles"},
  {"country":"SL","dial":"+232","name":"Sierra Leone"},
  {"country":"SG","dial":"+65","name":"Singapore"},
  {"country":"SX","dial":"+1","name":"Sint Maarten"},
  {"country":"SK","dial":"+421","name":"Slovakia"},
  {"country":"SI","dial":"+386","name":"Slovenia"},
  {"country":"SB","dial":"+677","name":"Solomon Islands"},
  {"country":"SO","dial":"+252","name":"Somalia"},
  {"country":"ZA","dial":"+27","name":"South Africa"},
  {"country":"KR","dial":"+82","name":"South Korea"},
  {"country":"SS","dial":"+211","name":"South Sudan"},
  {"country":"ES","dial":"+34","name":"Spain"},
  {"country":"LK","dial":"+94","name":"Sri Lanka"},
  {"country":"BL","dial":"+590","name":"St. Barthélemy"},
  {"country":"SH","dial":"+290","name":"St. Helena"},
  {"country":"KN","dial":"+1","name":"St. Kitts & Nevis"},
  {"country":"LC","dial":"+1","name":"St. Lucia"},
  {"country":"MF","dial":"+590","name":"St. Martin"},
  {"country":"PM","dial":"+508","name":"St. Pierre & Miquelon"},
  {"country":"VC","dial":"+1","name":"St. Vincent & Grenadines"},
  {"country":"SD","dial":"+249","name":"Sudan"},
  {"country":"SR","dial":"+597","name":"Suriname"},
  {"country":"SJ","dial":"+47","name":"Svalbard & Jan Mayen"},
  {"country":"SE","dial":"+46","name":"Sweden"},
  {"country":"CH","dial":"+41","name":"Switzerland"},
  {"country":"SY","dial":"+963","name":"Syria"},
  {"country":"TW","dial":"+886","name":"Taiwan"},
  {"country":"TJ","dial":"+992","name":"Tajikistan"},
  {"country":"TZ","dial":"+255","name":"Tanzania"},
  {"country":"TH","dial":"+66","name":"Thailand"},
  {"country":"TL","dial":"+670","name":"Timor-Leste"},
  {"country":"TG","dial":"+228","name":"Togo"},
  {"country":"TK","dial":"+690","name":"Tokelau"},
  {"country":"TO","dial":"+676","name":"Tonga"},
  {"country":"TT","dial":"+1","name":"Trinidad & Tobago"},
  {"country":"TA","dial":"+290","name":"Tristan da Cunha"},
  {"country":"TN","dial":"+216","name":"Tunisia"},
  {"country":"TR","dial":"+90","name":"Türkiye"},
  {"country":"TM","dial":"+993","name":"Turkmenistan"},
  {"country":"TC","dial":"+1","name":"Turks & Caicos Islands"},
  {"country":"TV","dial":"+688","name":"Tuvalu"},
  {"country":"VI","dial":"+1","name":"U.S. Virgin Islands"},
  {"country":"UG","dial":"+256","name":"Uganda"},
  {"country":"UA","dial":"+380","name":"Ukraine"},
  {"country":"AE","dial":"+971","name":"United Arab Emirates"},
  {"country":"GB","dial":"+44","name":"United Kingdom"},
  {"country":"US","dial":"+1","name":"United States"},
  {"country":"UY","dial":"+598","name":"Uruguay"},
  {"country":"UZ","dial":"+998","name":"Uzbekistan"},
  {"country":"VU","dial":"+678","name":"Vanuatu"},
  {"country":"VA","dial":"+39","name":"Vatican City"},
  {"country":"VE","dial":"+58","name":"Venezuela"},
  {"country":"VN","dial":"+84","name":"Vietnam"},
  {"country":"WF","dial":"+681","name":"Wallis & Futuna"},
  {"country":"EH","dial":"+212","name":"Western Sahara"},
  {"country":"YE","dial":"+967","name":"Yemen"},
  {"country":"ZM","dial":"+260","name":"Zambia"},
  {"country":"ZW","dial":"+263","name":"Zimbabwe"},
];
